package xyz.scottc.additionalthings;

import net.minecraftforge.common.ForgeConfigSpec;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber
public class Config {

    public static ForgeConfigSpec SERVER_CONFIG;
    public static ForgeConfigSpec CLIENT_CONFIG;
    private static final ForgeConfigSpec.Builder SERVER_BUILDER = new ForgeConfigSpec.Builder();
    private static final ForgeConfigSpec.Builder CLIENT_BUILDER = new ForgeConfigSpec.Builder();

    public static final String CATAGORY01_GENERAL = "General";
        public static ForgeConfigSpec.BooleanValue ENABLE_DIAMOND_GENERATOR;

    public static final String CATAGORY01_ENERGY = "Energy";
        public static final String CATAGORY02_DIAMOND_GENERATOR = "Diamond_Generator";
            public static ForgeConfigSpec.IntValue DIAMOND_GENERATOR_CAPACITY;
            public static ForgeConfigSpec.IntValue DIAMOND_GENERATOR_MAX_TRANSFER_PER_TICK;
            public static ForgeConfigSpec.IntValue DIAMOND_GENERATOR_FE_PER_DIAMOND;
            public static ForgeConfigSpec.IntValue DIAMOND_GENERATOR_TICKS_PER_DIAMOND;

    static {

        // Setup client config
        CLIENT_BUILDER.comment("General Settings").push(CATAGORY01_GENERAL);

        CLIENT_BUILDER.pop();

        // Setup server config
        SERVER_BUILDER.comment("General Settings").push(CATAGORY01_GENERAL);
        setupEnableBlocksConfig();
        SERVER_BUILDER.pop();

        SERVER_BUILDER.comment("Energy Settings").push(CATAGORY01_ENERGY);
        setupDiamondGeneratorConfig();
        SERVER_BUILDER.pop();

        SERVER_CONFIG = SERVER_BUILDER.build();
        CLIENT_CONFIG = CLIENT_BUILDER.build();
    }

    private static void setupEnableBlocksConfig() {
        ENABLE_DIAMOND_GENERATOR = SERVER_BUILDER.comment("True to enable the Diamond Generator")
                .define("Diamond_Generator", true);

    }

    private static void setupDiamondGeneratorConfig() {
        SERVER_BUILDER.comment("Diamond Generator energy settings").push(CATAGORY02_DIAMOND_GENERATOR);
        DIAMOND_GENERATOR_CAPACITY = SERVER_BUILDER.comment("The energy capacity for a diamond generator.")
                .defineInRange("Capacity", 100000, 0, Integer.MAX_VALUE);
        DIAMOND_GENERATOR_MAX_TRANSFER_PER_TICK = SERVER_BUILDER.comment("The max FE output per tick.")
                .defineInRange("Max_Transfer_Rate", 500, 0, Integer.MAX_VALUE);
        DIAMOND_GENERATOR_FE_PER_DIAMOND = SERVER_BUILDER.comment("The max FE generated by one diamond.")
                .defineInRange("Max_FE_Per_Diamond", 10000, 0, Integer.MAX_VALUE);
        DIAMOND_GENERATOR_TICKS_PER_DIAMOND = SERVER_BUILDER.comment("The ticks it takes to comsume a diamond.")
                .defineInRange("Ticks_Per_Diamond", 20 * 10, 1, Integer.MAX_VALUE);
        SERVER_BUILDER.pop();
    }
}
